/**
 * TypeScript type definitions for AEGIS Workflow Definitions
 * These types represent the JSON structure generated by Rust TemporalWorkflowMapper
 */

/**
 * Temporal Workflow Definition generated from AEGIS YAML
 */
export interface TemporalWorkflowDefinition {
  workflow_id: string;
  name: string;
  version: string;
  initial_state: string;
  context: Record<string, any>;
  states: Record<string, WorkflowState>;
}

/**
 * Individual state in the workflow FSM
 */
export interface WorkflowState {
  kind: StateKind;

  // Agent-specific fields
  agent?: string;
  input?: string;
  isolation?: 'firecracker' | 'docker' | 'process';
  timeout?: string;

  // System-specific fields
  command?: string;
  env?: Record<string, string>;
  workdir?: string;

  // Human-specific fields
  prompt?: string;
  default_response?: string;

  // ParallelAgents-specific fields
  agents?: ParallelAgentConfig[];
  consensus?: ConsensusConfig;

  // Transitions
  transitions: TransitionRule[];
}

/**
 * State kind enum
 */
export type StateKind = 'Agent' | 'System' | 'Human' | 'ParallelAgents';

/**
 * Parallel agent configuration
 */
export interface ParallelAgentConfig {
  agent: string;
  input: string;
  weight: number;
}

/**
 * Consensus configuration for ParallelAgents
 */
export interface ConsensusConfig {
  strategy: 'weighted_average' | 'majority_vote' | 'unanimous' | 'any_approved';
  threshold?: number;
  agreement?: number;
  n?: number;
}

/**
 * Transition rule for state machine
 */
export interface TransitionRule {
  condition: TransitionCondition;
  target: string | null; // null for terminal states
  threshold?: number;
  min?: number;
  max?: number;
  exit_code?: number;
  value?: string;
  expression?: string;
  feedback?: string;
}

/**
 * Transition condition types
 */
export type TransitionCondition =
  | 'always'
  | 'on_success'
  | 'on_failure'
  | 'exit_code_zero'
  | 'exit_code_non_zero'
  | 'exit_code'
  | 'score_above'
  | 'score_below'
  | 'score_between'
  | 'confidence_above'
  | 'score_and_confidence_above'
  | 'all_approved'
  | 'any_rejected'
  | 'input_equals'
  | 'input_equals_yes'
  | 'input_equals_no'
  | 'custom';

/**
 * Workflow input parameters
 */
export interface WorkflowInput {
  task?: string;
  agent_id?: string;
  judge_id?: string;
  command?: string;
  max_iterations?: number;
  validation_threshold?: number;
  [key: string]: any;
}

/**
 * Workflow result
 */
export interface WorkflowResult {
  status: 'completed' | 'failed' | 'cancelled' | 'timed_out';
  output?: any;
  error?: string;
  iterations?: number;
  final_state?: string;
  blackboard?: Record<string, any>;
}

/**
 * Blackboard for shared workflow context
 * Automatically persisted by Temporal with workflow state
 */
export type Blackboard = Record<string, any>;

/**
 * Agent execution result
 */
export interface AgentExecutionResult {
  execution_id: string;
  status: 'completed' | 'failed';
  output: string;
  error?: string;
  iterations: number;
}

/**
 * System command execution result
 */
export interface SystemCommandResult {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
}

/**
 * Validation result (gradient scoring)
 */
export interface ValidationResult {
  score: number; // 0.0 - 1.0
  confidence: number; // 0.0 - 1.0
  reasoning: string;
  binary_valid: boolean;
}

/**
 * Human input result
 */
export interface HumanInputResult {
  response: string;
  feedback?: string;
  received_at: string;
}

/**
 * Parallel agents consensus result
 */
export interface ConsensusResult {
  final_score: number;
  confidence: number;
  individual_scores: number[];
  individual_results: AgentExecutionResult[];
  agreement_level: number;
}

/**
 * gRPC Request/Response Types
 * These match the protobuf definitions in proto/aegis_runtime.proto
 */

/**
 * Request to execute an agent
 */
export interface ExecuteAgentRequest {
  agent_id: string;
  input?: string;
  context_json: string;
  timeout_seconds?: number;
}

/**
 * Execution event (streaming response)
 */
export interface ExecutionEvent {
  event_type: 'ExecutionStarted' | 'IterationStarted' | 'IterationCompleted' |
  'IterationFailed' | 'RefinementApplied' | 'ExecutionCompleted' |
  'ExecutionFailed';
  execution_id: string;
  timestamp: string;
  iteration_number?: number;
  action?: string;
  output?: string;
  error_message?: string;
  code_diff?: string;
  final_output?: string;
  reason?: string;
  total_iterations?: number;
}

/**
 * Request to execute a system command
 */
export interface ExecuteSystemCommandRequest {
  command: string;
  env?: Record<string, string>;
  workdir?: string;
  timeout_seconds?: number;
}

/**
 * Response from system command execution
 */
export interface ExecuteSystemCommandResponse {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
}

/**
 * Request to validate with judge agents
 */
export interface ValidateRequest {
  agent_output: string;
  judge_agent_ids: string[];
  context: Record<string, string>;
}

/**
 * Response from validation
 */
export interface ValidateResponse {
  final_score: number;
  confidence: number;
  individual_scores: number[];
  reasoning: string;
}

/**
 * Request to query Cortex for patterns (STUBBED)
 */
export interface QueryCortexRequest {
  error_signature: string;
  limit?: number;
}

/**
 * Cortex pattern (STUBBED)
 */
export interface CortexPattern {
  pattern_id: string;
  error_signature: string;
  solution_approach: string;
  success_rate: number;
  frequency: number;
}

/**
 * Response from Cortex pattern query (STUBBED)
 */
export interface QueryCortexResponse {
  patterns: CortexPattern[];
}

/**
 * Request to store a pattern in Cortex (STUBBED)
 */
export interface StoreCortexPatternRequest {
  error_signature: string;
  solution_approach: string;
  agent_id: string;
  execution_id: string;
}

/**
 * Response from storing Cortex pattern (STUBBED)
 */
export interface StoreCortexPatternResponse {
  pattern_id: string;
}
