/**
 * TypeScript type definitions for AEGIS Workflow Definitions
 * These types represent the JSON structure generated by Rust TemporalWorkflowMapper
 */

/**
 * Temporal Workflow Definition generated from AEGIS YAML
 */
export interface TemporalWorkflowDefinition {
  workflow_id: string;
  name: string;
  version: string;
  initial_state: string;
  context: Record<string, any>;
  states: Record<string, WorkflowState>;
}

/**
 * Judge configuration for per-state validation (ADR-016, ADR-049)
 */
export interface JudgeConfig {
  /** Agent identifier that will be spawned as a child execution */
  agent_id: string;
  /** Optional Handlebars input template for this judge */
  input_template?: string;
  /** Consensus weight for this judge (default: 1.0) */
  weight?: number;
}

/**
 * Individual state in the workflow FSM
 */
export interface WorkflowState {
  kind: StateKind;

  // Agent-specific fields
  agent?: string;
  input?: string;
  isolation?: 'firecracker' | 'docker' | 'process';
  timeout?: string;

  // Agent inner-loop validation (ADR-016 / ADR-017)
  /** Judges that validate each iteration output before advancing (per-state YAML declaration) */
  judges?: JudgeConfig[];
  /** Maximum iterations for the 100monkeys inner refinement loop (default: 10) */
  max_iterations?: number;
  /** Optional judge agent ID for pre-execution semantic tool validation (ADR-049 Pillar 1) */
  pre_execution_validator?: string;

  // System-specific fields
  command?: string;
  env?: Record<string, string>;
  workdir?: string;

  // Human-specific fields
  prompt?: string;
  default_response?: string;

  // ParallelAgents-specific fields
  agents?: ParallelAgentConfig[];
  consensus?: ConsensusConfig;
  /** Explicit judge agents for ParallelAgents consensus validation (ADR-016) */
  judges_for_parallel?: JudgeConfig[];

  // Transitions
  transitions: TransitionRule[];
}

/**
 * State kind enum
 */
export type StateKind = 'Agent' | 'System' | 'Human' | 'ParallelAgents';

/**
 * Parallel agent configuration
 */
export interface ParallelAgentConfig {
  agent: string;
  input: string;
  weight: number;
}

/**
 * Consensus configuration for ParallelAgents
 */
export interface ConsensusConfig {
  strategy: 'weighted_average' | 'majority_vote' | 'unanimous' | 'any_approved';
  threshold?: number;
  agreement?: number;
  n?: number;
}

/**
 * Transition rule for state machine
 */
export interface TransitionRule {
  condition: TransitionCondition;
  target: string | null; // null for terminal states
  threshold?: number;
  agreement?: number;
  min?: number;
  max?: number;
  exit_code?: number;
  value?: string;
  expression?: string;
  feedback?: string;
}

/**
 * Transition condition types
 */
export type TransitionCondition =
  | 'always'
  | 'on_success'
  | 'on_failure'
  | 'exit_code_zero'
  | 'exit_code_non_zero'
  | 'exit_code'
  | 'score_above'
  | 'score_below'
  | 'score_between'
  | 'confidence_above'
  | 'score_and_confidence_above'
  | 'consensus'
  | 'all_approved'
  | 'any_rejected'
  | 'input_equals'
  | 'input_equals_yes'
  | 'input_equals_no'
  | 'custom';

/**
 * Workflow input parameters
 */
export interface WorkflowInput {
  task?: string;
  agent_id?: string;
  judge_id?: string;
  command?: string;
  max_iterations?: number;
  validation_threshold?: number;
  [key: string]: any;
}

/**
 * Workflow result
 */
export interface WorkflowResult {
  status: 'completed' | 'failed' | 'cancelled' | 'timed_out';
  output?: any;
  error?: string;
  iterations?: number;
  final_state?: string;
  blackboard?: Record<string, any>;
}

/**
 * Blackboard for shared workflow context
 * Automatically persisted by Temporal with workflow state
 */
export type Blackboard = Record<string, any>;

/**
 * Agent execution result
 */
export interface AgentExecutionResult {
  execution_id: string;
  status: 'completed' | 'failed';
  output: string;
  error?: string;
  iterations: number;
}

/**
 * System command execution result
 */
export interface SystemCommandResult {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
}

/**
 * Validation result (gradient scoring)
 */
export interface ValidationResult {
  score: number; // 0.0 - 1.0
  confidence: number; // 0.0 - 1.0
  reasoning: string;
  binary_valid: boolean;
}

/**
 * Human input result
 */
export interface HumanInputResult {
  response: string;
  feedback?: string;
  received_at: string;
}

/**
 * Parallel agents consensus result
 */
export interface ConsensusResult {
  final_score: number;
  confidence: number;
  individual_scores: number[];
  individual_results: AgentExecutionResult[];
  agreement_level: number;
}

/**
 * gRPC Request/Response Types
 * These match the protobuf definitions in proto/aegis_runtime.proto
 */

/**
 * Request to execute an agent
 */
export interface ExecuteAgentRequest {
  agent_id: string;
  input?: string;
  context_json: string;
  timeout_seconds?: number;
  /** Maps to proto field workflow_execution_id (field 5). Used to link the child
   * execution back to the workflow execution in the Rust orchestrator so it can
   * be tracked under the correct WorkflowExecution aggregate.
   * NOTE: gRPC loader uses keepCase:true, so the name must match the proto exactly. */
  workflow_execution_id?: string;
}

/**
 * Execution event (streaming response)
 */
export interface ExecutionEvent {
  event_type: 'ExecutionStarted' | 'IterationStarted' | 'IterationCompleted' |
  'IterationFailed' | 'RefinementApplied' | 'ExecutionCompleted' |
  'ExecutionFailed';
  execution_id: string;
  timestamp: string;
  iteration_number?: number;
  action?: string;
  output?: string;
  error_message?: string;
  code_diff?: string;
  final_output?: string;
  reason?: string;
  total_iterations?: number;
}

/**
 * Request to execute a system command
 */
export interface ExecuteSystemCommandRequest {
  command: string;
  env?: Record<string, string>;
  workdir?: string;
  timeout_seconds?: number;
}

/**
 * Response from system command execution
 */
export interface ExecuteSystemCommandResponse {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
}

/**
 * Request to validate with judge agents
 * Field names match the proto definition (aegis_runtime.proto ValidateRequest)
 */
export interface ValidateRequest {
  /** The agent output to evaluate */
  output: string;
  /** Task description / evaluation criteria */
  task?: string;
  /** Judge agents to run (maps to repeated JudgeConfig in proto) */
  judges: JudgeConfig[];
  /** Consensus strategy configuration */
  consensus?: {
    strategy: string;
    threshold?: number;
    agreement?: number;
    n?: number;
  };
  /** Serialized JSON context string */
  context_json?: string;
}

/**
 * Response from validation
 * Field names match the proto definition (aegis_runtime.proto ValidateResponse)
 */
export interface ValidateResponse {
  score: number;             // 0.0 - 1.0
  confidence: number;        // 0.0 - 1.0
  reasoning: string;
  binary_valid: boolean;
  individual_results: JudgeResult[];
}

/**
 * Individual judge result
 */
export interface JudgeResult {
  judge_id: string;
  score: number;
  confidence: number;
  reasoning: string;
}

/**
 * Request to query Cortex for patterns (STUBBED)
 */
export interface QueryCortexRequest {
  error_signature: string;
  limit?: number;
}

/**
 * Cortex pattern (STUBBED)
 */
export interface CortexPattern {
  pattern_id: string;
  error_signature: string;
  solution_approach: string;
  success_rate: number;
  frequency: number;
}

/**
 * Response from Cortex pattern query (STUBBED)
 */
export interface QueryCortexResponse {
  patterns: CortexPattern[];
}

/**
 * Request to store a pattern in Cortex
 * Field names match proto StoreCortexPatternRequest
 */
export interface StoreCortexPatternRequest {
  error_signature: string;
  error_type?: string;
  error_message?: string;
  solution_approach: string;
  solution_code?: string;
  agent_id?: string;
  tags?: string[];
}

/**
 * Response from storing Cortex pattern
 */
export interface StoreCortexPatternResponse {
  pattern_id: string;
  deduplicated: boolean;
  new_frequency: number;
}

// ============================================================================
// ADR-049: Trajectory Pattern Types
// ============================================================================

/**
 * A single step in a tool-use trajectory
 * Matches proto TrajectoryStep
 */
export interface TrajectoryStep {
  /** Name of the tool that was invoked (e.g. 'cmd.run', 'filesystem.write') */
  tool_name: string;
  /** JSON-serialized arguments passed to the tool */
  arguments_json: string;
}

/**
 * Request to store a successful tool-use trajectory in Cortex (ADR-049 Pillar 2)
 * Matches proto StoreTrajectoryPatternRequest
 */
export interface StoreTrajectoryPatternRequest {
  /** Task description or execution_id used as deduplication key */
  task_signature: string;
  /** Ordered sequence of tool calls that led to success */
  steps: TrajectoryStep[];
  /** Validation score that triggered trajectory capture (0.0–1.0) */
  success_score: number;
}

/**
 * Response from storing a trajectory pattern
 * Matches proto StoreTrajectoryPatternResponse
 */
export interface StoreTrajectoryPatternResponse {
  trajectory_id: string;
  new_weight: number;
  deduplicated: boolean;
}
