/**
 * TypeScript type definitions for AEGIS Workflow Definitions
 * These types represent the JSON structure generated by Rust TemporalWorkflowMapper
 */

/**
 * Storage class for a workflow-level volume declaration (ADR-050)
 */
export type WorkflowStorageClass = "ephemeral" | "persistent";

/**
 * Output handler configuration — egress mechanism fired after state/execution completes.
 * ADR-103: Agent Output Handler.
 */
export type OutputHandlerConfig =
  | {
      type: "agent";
      agent_id: string;
      input_template?: string;
      timeout_seconds?: number;
      required: boolean;
    }
  | {
      type: "container";
      image: string;
      command: string[];
      env?: Record<string, string>;
      required: boolean;
    }
  | {
      type: "mcp_tool";
      tool_name: string;
      arguments: Record<string, unknown>;
      timeout_seconds?: number;
      required: boolean;
    }
  | {
      type: "webhook";
      url: string;
      method?: string;
      headers?: Record<string, string>;
      body_template?: string;
      timeout_seconds?: number;
      required: boolean;
    };

/**
 * Named volume declared in spec.volumes (ADR-050)
 * Forwarded from Rust TemporalWorkflowDefinition.spec_storage.shared_volumes.
 */
export interface WorkflowVolumeSpec {
  name: string;
  storage_class: WorkflowStorageClass;
  size_limit_bytes?: number;
}

/**
 * Volume mount binding for a ContainerRun step (ADR-050)
 * References a volume declared in spec.volumes by name.
 */
export interface ContainerVolumeMount {
  name: string;
  mount_path: string;
  read_only: boolean;
}

/**
 * Resource limits for a ContainerRun step (ADR-050)
 */
export interface ContainerResources {
  /** CPU quota in millicores (e.g. 1000 = 1 vCPU) */
  cpu?: number;
  /** Memory limit as a string (e.g. "512Mi", "2Gi") */
  memory?: string;
  /** Wall-clock timeout as a human-readable duration string (e.g. "10m", "1h") */
  timeout?: string;
}

/**
 * Retry configuration for a ContainerRun step (ADR-050)
 */
export interface RetryConfig {
  max_attempts?: number;
  backoff?: string;
}

/**
 * Configuration for a single step in ParallelContainerRun (ADR-050)
 */
export interface ContainerRunConfig {
  name: string;
  image: string;
  command: string[];
  env?: Record<string, string>;
  workdir?: string;
  volumes?: ContainerVolumeMount[];
  resources?: ContainerResources;
  registry_credentials?: string;
  shell?: boolean;
}

/**
 * gRPC request for ExecuteContainerRun (ADR-050)
 * Maps directly to proto ExecuteContainerRunRequest.
 */
export interface ExecuteContainerRunRequest {
  execution_id: string;
  name: string;
  image: string;
  image_pull_policy?: string;
  command: string[];
  env?: Record<string, string>;
  workdir?: string;
  volumes?: ContainerVolumeMount[];
  resources?: ContainerResources;
  registry_credentials?: string;
  shell?: boolean;
  state_name: string;
  max_attempts?: number;
  /** Security context name for policy enforcement. */
  security_context_name?: string;
  /** The workflow execution ID for correlating container runs back to their parent workflow. */
  workflow_execution_id?: string;
}

/**
 * gRPC response from ExecuteContainerRun (ADR-050)
 * Maps directly to proto ExecuteContainerRunResponse.
 */
export interface ExecuteContainerRunResponse {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
  attempts: number;
}

/**
 * Workspace volume specification for a workflow (ADR-087)
 * Declares how the workflow provisions shared storage for its steps.
 */
export interface WorkflowWorkspaceSpec {
  storage_class: "ephemeral" | "persistent";
  ttl_hours?: number;
  size_limit_mb?: number;
  volume_id?: string;
  blackboard_key?: string;
}

/**
 * Workflow-level storage configuration (WORKFLOW_MANIFEST_SPEC_V1 §spec.storage).
 */
export interface WorkflowStorageSpec {
  workspace?: WorkflowWorkspaceSpec;
  shared_volumes?: WorkflowVolumeSpec[];
}

/**
 * Temporal Workflow Definition generated from AEGIS YAML
 */
export interface TemporalWorkflowDefinition {
  workflow_id: string;
  tenant_id: string;
  name: string;
  version: string;
  initial_state: string;
  context: Record<string, any>;
  states: Record<string, WorkflowState>;
  /** Workflow-level storage configuration (WORKFLOW_MANIFEST_SPEC_V1 §spec.storage) */
  spec_storage?: WorkflowStorageSpec;
  /** Visibility scope for this workflow definition (ADR-076) */
  scope?: "global" | "tenant";
  /** Maximum total state transitions before the workflow terminates.
   *  Default: 50. Ceiling: 100. */
  max_total_transitions?: number;
}

/**
 * Judge configuration for per-state validation (ADR-016, ADR-049)
 */
export interface JudgeConfig {
  /** Agent identifier that will be spawned as a child execution */
  agent_id: string;
  /** Optional Handlebars input template for this judge */
  input_template?: string;
  /** Consensus weight for this judge (default: 1.0) */
  weight?: number;
}

/**
 * Individual state in the workflow FSM
 */
export interface WorkflowState {
  kind: StateKind;

  // Agent-specific fields
  agent?: string;
  input?: string;
  /** Optional per-state intent template (Handlebars). Rendered against blackboard
   *  and passed as ExecuteAgentRequest.intent — the natural-language steering for
   *  the agent. Falls back to the workflow-level intent (blackboard.intent) when
   *  absent. ADR-092. */
  intent?: string;
  isolation?: "inherit" | "firecracker" | "docker" | "process";
  timeout?: string;

  // Agent inner-loop validation (ADR-016 / ADR-017)
  /** Judges that validate each iteration output before advancing (per-state YAML declaration) */
  judges?: JudgeConfig[];
  /** Maximum iterations for the 100monkeys inner refinement loop (default: 10) */
  max_iterations?: number;
  /** Optional judge agent ID for pre-execution semantic tool validation (ADR-049 Pillar 1) */
  pre_execution_validator?: string;

  // System-specific fields
  command?: string;
  env?: Record<string, string>;
  workdir?: string;

  // Human-specific fields
  prompt?: string;
  default_response?: string;

  // ParallelAgents-specific fields
  agents?: ParallelAgentConfig[];
  consensus?: ConsensusConfig;
  /** Explicit judge agents for ParallelAgents consensus validation (ADR-016) */
  judges_for_parallel?: JudgeConfig[];

  // ContainerRun-specific fields (ADR-050)
  container_run_name?: string;
  container_run_image?: string;
  container_run_image_pull_policy?: string;
  container_run_command?: string[];
  container_run_env?: Record<string, string>;
  container_run_workdir?: string;
  container_run_volumes?: ContainerVolumeMount[];
  container_run_resources?: ContainerResources;
  container_run_registry_credentials?: string;
  container_run_retry?: RetryConfig;
  container_run_shell?: boolean;

  // ParallelContainerRun-specific fields (ADR-050)
  parallel_container_steps?: ContainerRunConfig[];
  parallel_container_completion?: "all_succeed" | "any_succeed" | "best_effort";

  // Subworkflow-specific (ADR-065)
  subworkflow_id?: string;
  subworkflow_mode?: "blocking" | "fire_and_forget";
  subworkflow_result_key?: string;
  subworkflow_input?: string;

  // Output handler — egress mechanism fired after state execution (ADR-103)
  output_handler?: OutputHandlerConfig;

  /** Maximum number of times this state can be visited before the workflow terminates.
   *  Prevents infinite retry loops in FSMs with backward transitions.
   *  Default: 5. Ceiling: 20. */
  max_state_visits?: number;

  // Transitions
  transitions: TransitionRule[];
}

/**
 * State kind enum
 */
export type StateKind =
  | "Agent"
  | "System"
  | "Human"
  | "ParallelAgents"
  | "ContainerRun"
  | "ParallelContainerRun"
  | "Subworkflow";

/**
 * Parallel agent configuration
 */
export interface ParallelAgentConfig {
  agent: string;
  input: string;
  weight: number;
}

/**
 * Consensus configuration for ParallelAgents
 */
export interface ConsensusConfig {
  strategy: "weighted_average" | "majority_vote" | "unanimous" | "best_of_n";
  threshold?: number;
  agreement?: number;
  n?: number;
}

/**
 * Transition rule for state machine
 */
export interface TransitionRule {
  condition: TransitionCondition;
  target: string | null; // null for terminal states
  threshold?: number;
  agreement?: number;
  min?: number;
  max?: number;
  exit_code?: number;
  value?: string;
  expression?: string;
  feedback?: string;
}

/**
 * Transition condition types
 */
export type TransitionCondition =
  | "always"
  | "on_success"
  | "on_failure"
  | "exit_code_zero"
  | "exit_code_non_zero"
  | "exit_code"
  | "score_above"
  | "score_below"
  | "score_between"
  | "confidence_above"
  | "score_and_confidence_above"
  | "consensus"
  | "all_approved"
  | "any_rejected"
  | "input_equals"
  | "input_equals_yes"
  | "input_equals_no"
  | "custom";

/**
 * Workflow input parameters
 */
export interface WorkflowInput {
  task?: string;
  agent_id?: string;
  judge_id?: string;
  command?: string;
  max_iterations?: number;
  validation_threshold?: number;
  /** Tenant slug derived from JWT; scopes all execution artifacts to the tenant. */
  tenant_id?: string;
  /** Security context name for policy enforcement (e.g. "default", "restricted"). */
  security_context_name?: string;
  [key: string]: any;
}

/**
 * Workflow result
 */
export interface WorkflowResult {
  status: "completed" | "failed" | "cancelled" | "timed_out";
  output?: any;
  error?: string;
  iterations?: number;
  final_state?: string;
  blackboard?: Record<string, any>;
}

/**
 * Blackboard for shared workflow context
 * Automatically persisted by Temporal with workflow state
 */
export type Blackboard = Record<string, any>;

/**
 * Agent execution result
 */
export interface AgentExecutionResult {
  execution_id: string;
  status: "completed" | "failed";
  output: string;
  error?: string;
  iterations: number;
}

/**
 * System command execution result
 */
export interface SystemCommandResult {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
}

/**
 * Validation result (gradient scoring)
 */
export interface ValidationResult {
  score: number; // 0.0 - 1.0
  confidence: number; // 0.0 - 1.0
  reasoning: string;
  binary_valid: boolean;
}

/**
 * Human input result
 */
export interface HumanInputResult {
  response: string;
  feedback?: string;
  received_at: string;
}

/**
 * Parallel agents consensus result
 */
export interface ConsensusResult {
  final_score: number;
  confidence: number;
  individual_scores: number[];
  individual_results: AgentExecutionResult[];
  agreement_level: number;
}

/**
 * gRPC Request/Response Types
 * These match the protobuf definitions in proto/aegis_runtime.proto
 */

/**
 * Request to execute an agent
 */
export interface ExecuteAgentRequest {
  agent_id: string;
  input?: string;
  context_json: string;
  timeout_seconds?: number;
  /** Maps to proto field workflow_execution_id (field 5). Used to correlate the
   * execution with the parent workflow for lineage and observability without
   * changing execution semantics.
   * NOTE: gRPC loader uses keepCase:true, so the name must match the proto exactly. */
  workflow_execution_id?: string;
  /** Maps to proto field parent_execution_id (field 6). Only set for explicit
   * child-execution spawn paths (for example, judge agents or nested workflow
   * children). Do not set this for normal workflow-managed agent states. */
  parent_execution_id?: string;
  /** Tenant slug derived from JWT; scopes execution to the identified tenant.
   * Maps to proto field tenant_id (field 7). */
  tenant_id?: string;
  /** Security context name for policy enforcement.
   * Maps to proto field security_context_name (field 8). */
  security_context_name?: string;
  /** Workflow workspace volume ID to mount into the agent container.
   * When set, the runtime mounts this volume so the agent writes into the
   * shared workspace that subsequent workflow steps can read.
   * Maps to proto field workspace_volume_id (field 10). */
  workspace_volume_id?: string;
  /** Container path at which the workspace volume is mounted.
   * Defaults to /workspace when workspace_volume_id is provided.
   * Maps to proto field workspace_volume_mount_path (field 11). */
  workspace_volume_mount_path?: string;
  /** NFS remote path for the workspace volume in SeaweedFS.
   * When set, used directly for NFS registration instead of constructing a path.
   * Maps to proto field workspace_remote_path (field 12). */
  workspace_remote_path?: string;
  /** Natural-language steering for the agent ("why"). Distinct from input ("what").
   * Maps to proto field intent (ADR-092). */
  intent?: string;
}

/**
 * Execution event (streaming response)
 */
export interface ExecutionEvent {
  event_type:
    | "ExecutionStarted"
    | "IterationStarted"
    | "IterationCompleted"
    | "IterationFailed"
    | "RefinementApplied"
    | "ExecutionCompleted"
    | "ExecutionFailed";
  execution_id: string;
  timestamp: string;
  iteration_number?: number;
  action?: string;
  output?: string;
  error_message?: string;
  code_diff?: string;
  final_output?: string;
  reason?: string;
  total_iterations?: number;
}

/**
 * Request to execute a system command
 */
export interface ExecuteSystemCommandRequest {
  command: string;
  env?: Record<string, string>;
  workdir?: string;
  timeout_seconds?: number;
}

/**
 * Response from system command execution
 */
export interface ExecuteSystemCommandResponse {
  exit_code: number;
  stdout: string;
  stderr: string;
  duration_ms: number;
}

/**
 * Request to validate with judge agents
 * Field names match the proto definition (aegis_runtime.proto ValidateRequest)
 */
export interface ValidateRequest {
  /** The agent output to evaluate */
  output: string;
  /** Task description / evaluation criteria */
  task?: string;
  /** Judge agents to run (maps to repeated JudgeConfig in proto) */
  judges: JudgeConfig[];
  /** Consensus strategy configuration */
  consensus?: {
    strategy: string;
    threshold?: number;
    agreement?: number;
    n?: number;
  };
  /** Serialized JSON context string */
  context_json?: string;
  /** Security context name for policy enforcement. */
  security_context_name?: string;
}

/**
 * Response from validation
 * Field names match the proto definition (aegis_runtime.proto ValidateResponse)
 */
export interface ValidateResponse {
  score: number; // 0.0 - 1.0
  confidence: number; // 0.0 - 1.0
  reasoning: string;
  binary_valid: boolean;
  individual_results: JudgeResult[];
}

/**
 * Individual judge result
 */
export interface JudgeResult {
  judge_id: string;
  score: number;
  confidence: number;
  reasoning: string;
}

/**
 * Request to query Cortex for patterns
 */
export interface QueryCortexRequest {
  error_signature: string;
  limit?: number;
}

/**
 * Cortex pattern
 */
export interface CortexPattern {
  pattern_id: string;
  error_signature: string;
  solution_approach: string;
  success_rate: number;
  frequency: number;
}

/**
 * Response from Cortex pattern query
 */
export interface QueryCortexResponse {
  patterns: CortexPattern[];
}

/**
 * Request to store a pattern in Cortex
 * Field names match proto StoreCortexPatternRequest
 */
export interface StoreCortexPatternRequest {
  error_signature: string;
  error_type?: string;
  error_message?: string;
  solution_approach: string;
  solution_code?: string;
  agent_id?: string;
  tags?: string[];
}

/**
 * Response from storing Cortex pattern
 */
export interface StoreCortexPatternResponse {
  pattern_id: string;
  deduplicated: boolean;
  new_frequency: number;
}

// ============================================================================
// ADR-049: Trajectory Pattern Types
// ============================================================================

/**
 * A single step in a tool-use trajectory
 * Matches proto TrajectoryStep
 */
export interface TrajectoryStep {
  /** Name of the tool that was invoked (e.g. 'cmd.run', 'filesystem.write') */
  tool_name: string;
  /** JSON-serialized arguments passed to the tool */
  arguments_json: string;
}

/**
 * Request to store a successful tool-use trajectory in Cortex (ADR-049 Pillar 2)
 * Matches proto StoreTrajectoryPatternRequest
 */
export interface StoreTrajectoryPatternRequest {
  /** Task description or execution_id used as deduplication key */
  task_signature: string;
  /** Ordered sequence of tool calls that led to success */
  steps: TrajectoryStep[];
  /** Validation score that triggered trajectory capture (0.0–1.0) */
  success_score: number;
}

/**
 * Response from storing a trajectory pattern
 * Matches proto StoreTrajectoryPatternResponse
 */
export interface StoreTrajectoryPatternResponse {
  trajectory_id: string;
  new_weight: number;
  deduplicated: boolean;
}

/**
 * gRPC request for InvokeOutputHandler (ADR-103)
 * Maps directly to proto InvokeOutputHandlerRequest.
 */
export interface InvokeOutputHandlerRequest {
  execution_id: string;
  tenant_id: string;
  final_output: string;
  handler_config_json: string;
}

/**
 * gRPC response from InvokeOutputHandler (ADR-103)
 * Maps directly to proto InvokeOutputHandlerResponse.
 */
export interface InvokeOutputHandlerResponse {
  success: boolean;
  result: string;
  error: string;
}
